# Generated by Django 4.1.1 on 2022-11-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_alter_city_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
