# Generated by Django 4.1.1 on 2022-11-09 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Task')),
                ('on_create', models.DateTimeField(auto_now=True)),
                ('on_modified', models.DateTimeField(auto_now_add=True, null=True)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='todo_app.tag')),
            ],
        ),
    ]
