# Generated by Django 4.1.1 on 2022-11-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_city_icon_city_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
